#!/usr/bin/env bash
jekyll build && chmod -R a+r _site/ && rsync -apvvz --delete _site/ reflowst@reflowster.com:~/flickerstrip.com/
ssh -t reflowst@reflowster.com 'chmod -R o-w /home/reflowst/flickerstrip.com/; chmod -R g-w /home/reflowst/flickerstrip.com/'
